language: node_js
node_js:
  - "14"
  - "16"
  - "18"

branches:
  only:
    - master
    - 1.x

addons:
  code_climate:
    repo_token: 75dc20817d25bb52614e495f87d69b228edac0016fb096ccab2a75b624c68d4e

before_script:
  - npm install -g codeclimate-test-reporter

after_script:
  - gulp coverage
  - codeclimate < ./coverage/lcov.info
